spring:
  datasource:
    username: sa
    initialization-mode: always
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  application:
    name: car-rental
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
    security:
      basic:
        enabled: false
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 1
    key-prefix: "api1:"
server:
  servlet:
    session:
      timeout: 20m
  port: '8090'